import type { ResumeConfig, GitRepository, GitHubPR } from "../types/index.js";

/**
 * Content section generated by a plugin
 * Each plugin outputs one or more sections that get aggregated into the final resume prompt
 */
export interface PluginContentSection {
  /** Section title (e.g., "Pull Requests", "Code Contributions") */
  title: string;
  /** Markdown content for this section */
  content: string;
  /** Priority for ordering sections (lower = appears earlier) */
  priority: number;
  /** Estimated token count for AI prompt budgeting */
  tokenEstimate: number;
  /** Source plugin ID */
  sourcePlugin: string;
}

/**
 * Map of plugin IDs to their output types
 * Used for type-safe dependency passing between plugins
 */
export interface PluginOutputMap {
  git: GitPluginOutput;
  github: GitHubPluginOutput;
  "slack-ai": SlackAIPluginOutput;
  template: TemplatePluginOutput;
  language: LanguagePluginOutput;
}

/**
 * Git plugin output - provides repository and commit data
 */
export interface GitPluginOutput {
  repositories: GitRepository[];
}

/**
 * GitHub plugin output - provides PR data
 */
export interface GitHubPluginOutput {
  pullRequests: GitHubPR[];
}

/**
 * Slack AI plugin output - provides Slack context from AI export
 */
export interface SlackAIPluginOutput {
  slackContext: string;
}

/**
 * Template plugin output - provides resume template example
 */
export interface TemplatePluginOutput {
  templateContent: string;
}

/**
 * Language plugin output - provides output language preference
 */
export interface LanguagePluginOutput {
  language: string;
}

/**
 * Helper type to get the dependencies object for a plugin
 * Based on its `needs` array
 */
export type DepsFor<TNeeds extends (keyof PluginOutputMap)[]> = {
  [K in TNeeds[number]]: PluginOutputMap[K];
};

/**
 * Result returned by a plugin's generateContent method
 */
export interface PluginResult<TId extends keyof PluginOutputMap> {
  /** Content sections for the AI prompt */
  sections: PluginContentSection[];
  /** Typed output for dependent plugins */
  output: PluginOutputMap[TId];
}

/**
 * Options passed to promptForConfig
 */
export interface PromptConfigOptions {
  /** If true, re-prompt even if already configured */
  reset?: boolean;
}

/**
 * Base interface for all plugins
 *
 * A plugin is responsible for:
 * 1. Prompting for configuration (saved to config file)
 * 2. Deciding if it can run based on config and dependencies
 * 3. Generating content sections for the resume
 *
 * @template TId - The plugin's ID from PluginOutputMap
 * @template TNeeds - Array of plugin IDs this plugin depends on
 */
export interface PluginPrompt<
  TId extends keyof PluginOutputMap,
  TNeeds extends (keyof PluginOutputMap)[] = [],
> {
  /** Unique identifier for this plugin */
  readonly id: TId;

  /** Human-readable name (e.g., "Git Commits") */
  readonly name: string;

  /** Array of plugin IDs this plugin depends on */
  readonly needs: TNeeds;

  /**
   * Config keys that contain sensitive data (tokens, passwords).
   * Used by config command to mask values in output.
   */
  readonly sensitiveConfigKeys?: (keyof ResumeConfig)[];

  /**
   * Prompt user for configuration and return updated config
   * This is called during the config phase and saved to disk
   *
   * @param config Current configuration
   * @param options Prompt options (e.g., reset flag)
   * @returns Updated configuration (or same if no changes)
   */
  promptForConfig(config: ResumeConfig, options?: PromptConfigOptions): Promise<ResumeConfig>;

  /**
   * Check if this plugin can run based on config and dependency outputs
   *
   * @param config Current configuration
   * @param deps Outputs from dependencies (type-safe based on `needs`)
   * @returns true if the plugin should run
   */
  canRun(config: ResumeConfig, deps: DepsFor<TNeeds>): boolean;

  /**
   * Generate content sections for the resume
   *
   * @param config Current configuration
   * @param deps Outputs from dependencies (type-safe based on `needs`)
   * @returns Result with sections and typed output, or null if generation failed
   */
  generateContent(
    config: ResumeConfig,
    deps: DepsFor<TNeeds>,
  ): Promise<PluginResult<TId> | null>;
}

/**
 * Type for any plugin (used in collections)
 */
export type AnyPlugin = PluginPrompt<keyof PluginOutputMap, (keyof PluginOutputMap)[]>;

/**
 * Runtime state for plugin execution
 * Stores outputs from plugins that have run
 */
export type PluginOutputs = Partial<{
  [K in keyof PluginOutputMap]: PluginOutputMap[K];
}>;
